CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.NOTIFICATION;

CREATE TABLE IF NOT EXISTS FERN_REPORTING.NOTIFICATION.ALERT_RULE (
    ALERT_RULE_ID NUMBER(38, 0) AUTOINCREMENT,
    RULE_NAME VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    CONDITION_EXPRESSION VARCHAR,
    NOTIFICATION_CHANNEL VARCHAR NOT NULL,
    RECIPIENTS VARIANT,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ALERT_RULE_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.NOTIFICATION.WEBHOOK_ENDPOINT (
    WEBHOOK_ENDPOINT_ID NUMBER(38, 0) AUTOINCREMENT,
    ENDPOINT_URL VARCHAR NOT NULL,
    EVENT_TYPES VARIANT NOT NULL,
    SECRET_KEY_REF VARCHAR,
    STATUS VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (WEBHOOK_ENDPOINT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.NOTIFICATION.NOTIFICATION_JOB (
    NOTIFICATION_JOB_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR,
    SOURCE_SERVICE VARCHAR,
    EVENT_TYPE VARCHAR,
    OCCURRED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR,
    NOTIFICATION_TYPE VARCHAR NOT NULL,
    CHANNEL VARCHAR NOT NULL,
    RECIPIENT VARCHAR,
    SUBJECT VARCHAR,
    BODY VARCHAR,
    STATUS VARCHAR NOT NULL,
    SCHEDULED_AT TIMESTAMP_TZ,
    SENT_AT TIMESTAMP_TZ,
    DELIVERED_AT TIMESTAMP_TZ,
    PAYLOAD VARIANT,
    PRIMARY KEY (NOTIFICATION_JOB_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.NOTIFICATION.DELIVERY_ATTEMPT (
    DELIVERY_ATTEMPT_ID NUMBER(38, 0) AUTOINCREMENT,
    NOTIFICATION_JOB_ID NUMBER(38, 0) NOT NULL,
    ATTEMPT_NUMBER NUMBER(10, 0) NOT NULL,
    ATTEMPT_TIMESTAMP TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR NOT NULL,
    ERROR_MESSAGE VARCHAR,
    RESPONSE_CODE VARCHAR,
    PRIMARY KEY (DELIVERY_ATTEMPT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.NOTIFICATION.WEBHOOK_DELIVERY_LOG (
    WEBHOOK_DELIVERY_LOG_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR,
    SOURCE_SERVICE VARCHAR,
    EVENT_TYPE VARCHAR,
    OCCURRED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR,
    WEBHOOK_ENDPOINT_ID NUMBER(38, 0) NOT NULL,
    DELIVERY_STATUS VARCHAR NOT NULL,
    ATTEMPT_COUNT NUMBER(10, 0) NOT NULL DEFAULT 0,
    LAST_ATTEMPT_AT TIMESTAMP_TZ,
    DELIVERED_AT TIMESTAMP_TZ,
    PAYLOAD VARIANT,
    PRIMARY KEY (WEBHOOK_DELIVERY_LOG_ID)
);
