CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.RAW_EVENTS;
CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.REPORT;

CREATE TABLE IF NOT EXISTS FERN_REPORTING.RAW_EVENTS.EVENT_LANDING (
    LANDING_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    PARTITION_KEY VARCHAR,
    KAFKA_TOPIC VARCHAR,
    KAFKA_PARTITION NUMBER(38, 0),
    KAFKA_OFFSET NUMBER(38, 0),
    PAYLOAD VARIANT NOT NULL,
    PRIMARY KEY (LANDING_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.SALES_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    SALE_ORDER_ID NUMBER(38, 0),
    PRODUCT_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    QTY NUMBER(18, 4) NOT NULL DEFAULT 0,
    GROSS_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    DISCOUNT_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    TAX_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    NET_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.PAYMENT_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    SALE_ORDER_ID NUMBER(38, 0),
    PAYMENT_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    PAYMENT_METHOD VARCHAR,
    PAYMENT_STATUS VARCHAR,
    AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.INVENTORY_MOVEMENT_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    INGREDIENT_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    MOVEMENT_TYPE VARCHAR NOT NULL,
    QTY_CHANGE NUMBER(18, 4) NOT NULL DEFAULT 0,
    UNIT_COST NUMBER(18, 2),
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.PROCUREMENT_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    SUPPLIER_ID NUMBER(38, 0),
    PURCHASE_ORDER_ID NUMBER(38, 0),
    GOODS_RECEIPT_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    FACT_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.ATTENDANCE_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    EMPLOYEE_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    ATTENDANCE_STATUS VARCHAR,
    WORK_HOURS NUMBER(10, 2) DEFAULT 0,
    OVERTIME_HOURS NUMBER(10, 2) DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.PAYROLL_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    EMPLOYEE_ID NUMBER(38, 0),
    PAYROLL_RUN_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    GROSS_PAY NUMBER(18, 2) DEFAULT 0,
    NET_PAY NUMBER(18, 2) DEFAULT 0,
    TAX_AMOUNT NUMBER(18, 2) DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.EXPENSE_FACT (
    FACT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    EXPENSE_RECORD_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    SOURCE_TYPE VARCHAR,
    AMOUNT NUMBER(18, 2) DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (FACT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.REGION_DAILY_SUMMARY (
    SUMMARY_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0) NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    TOTAL_SALES NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_PROCUREMENT NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_EXPENSE NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_PAYROLL NUMBER(18, 2) NOT NULL DEFAULT 0,
    TRANSACTION_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (SUMMARY_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.COMPANY_DAILY_SUMMARY (
    SUMMARY_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    BUSINESS_DATE DATE NOT NULL,
    TOTAL_SALES NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_PROCUREMENT NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_EXPENSE NUMBER(18, 2) NOT NULL DEFAULT 0,
    TOTAL_PAYROLL NUMBER(18, 2) NOT NULL DEFAULT 0,
    OUTLET_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
    PAYLOAD VARIANT,
    PRIMARY KEY (SUMMARY_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.REPORT.EXPORT_JOB (
    EXPORT_JOB_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR,
    SOURCE_SERVICE VARCHAR,
    EVENT_TYPE VARCHAR,
    OCCURRED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR,
    REPORT_TYPE VARCHAR NOT NULL,
    FORMAT VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    REQUESTED_BY VARCHAR,
    FILE_PATH VARCHAR,
    COMPLETED_AT TIMESTAMP_TZ,
    PAYLOAD VARIANT,
    PRIMARY KEY (EXPORT_JOB_ID)
);
