export const permissionConstants = {
  admin: 'iam.user.read',
  iam: {
    userRead: 'iam.user.read',
    userWrite: 'iam.user.write',
    roleRead: 'iam.role.read',
    roleWrite: 'iam.role.write',
    roleAssign: 'iam.role.assign',
    scopeAssign: 'iam.scope.assign',
    permissionRead: 'iam.permission.read',
    permissionOverrideRead: 'iam.permission_override.read',
    permissionOverrideWrite: 'iam.permission_override.write',
  },
  catalog: {
    productRead: 'catalog.product.read',
    ingredientRead: 'catalog.ingredient.read',
    recipeRead: 'catalog.recipe.read',
    priceRead: 'catalog.price.read',
  },
  org: {
    regionRead: 'org.region.read',
    regionWrite: 'org.region.write',
    outletRead: 'org.outlet.read',
    outletWrite: 'org.outlet.write',
  },
  pos: {
    sessionRead: 'pos.session.read',
    orderRead: 'pos.order.read',
    orderCreate: 'pos.order.create',
  },
  procurement: {
    supplierRead: 'procurement.supplier.read',
    supplierWrite: 'procurement.supplier.write',
    invoiceRead: 'procurement.invoice.read',
    invoiceReview: 'procurement.invoice.review',
    invoiceApprove: 'procurement.invoice.approve',
    invoiceDispute: 'procurement.invoice.dispute',
    paymentRead: 'procurement.payment.read',
    paymentRecord: 'procurement.payment.record',
    purchaseOrderRead: 'procurement.po.read',
    purchaseOrderCreate: 'procurement.po.create',
    goodsReceiptRead: 'procurement.gr.read',
    goodsReceiptCreate: 'procurement.gr.create',
  },
  inventory: {
    balanceRead: 'inventory.balance.read',
    ledgerRead: 'inventory.ledger.read',
    adjustmentWrite: 'inventory.adjustment.write',
  },
  hr: {
    employeeRead: 'hr.employee.read',
    employeeWrite: 'hr.employee.write',
    contractRead: 'hr.contract.read',
    contractDetailRead: 'hr.contract.detail.read',
    contractWrite: 'hr.contract.write',
    shiftRead: 'hr.shift.read',
    shiftWrite: 'hr.shift.write',
    attendanceWrite: 'hr.attendance.write',
    attendanceReview: 'hr.attendance.review',
    payrollPrepare: 'hr.payroll.prepare',
  },
  finance: {
    payrollRead: 'finance.payroll.read',
    payrollDetailRead: 'finance.payroll.detail.read',
    payrollPrepare: 'finance.payroll.prepare',
    payrollApprove: 'finance.payroll.approve',
    payrollPay: 'finance.payroll.pay',
    configRead: 'finance.config.read',
    configWrite: 'finance.config.write',
  },
  audit: {
    read: 'audit.read',
    detailRead: 'audit.detail.read',
  },
  report: {
    read: 'report.read',
    export: 'report.export',
    payrollRead: 'report.payroll.read',
    payrollExport: 'report.payroll.export',
  },
} as const
