CREATE DATABASE IF NOT EXISTS FERN_REPORTING;

CREATE WAREHOUSE IF NOT EXISTS FERN_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS FERN_BI_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.RAW_EVENTS;
CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.REPORT;
CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.FINANCE_PROJECTION;
CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.AUDIT;
CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.NOTIFICATION;
