CREATE WAREHOUSE IF NOT EXISTS ${ingestWarehouse}
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ${biWarehouse}
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ${reportingDatabase};

CREATE SCHEMA IF NOT EXISTS ${reportingDatabase}.RAW_EVENTS;
CREATE SCHEMA IF NOT EXISTS ${reportingDatabase}.REPORT;
CREATE SCHEMA IF NOT EXISTS ${reportingDatabase}.FINANCE_PROJECTION;
CREATE SCHEMA IF NOT EXISTS ${reportingDatabase}.AUDIT;
CREATE SCHEMA IF NOT EXISTS ${reportingDatabase}.NOTIFICATION;
