CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.AUDIT;

CREATE TABLE IF NOT EXISTS FERN_REPORTING.AUDIT.AUDIT_EVENT (
    AUDIT_EVENT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    CORRELATION_ID VARCHAR,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    USER_ID NUMBER(38, 0),
    ACTION VARCHAR,
    RESOURCE_TYPE VARCHAR,
    RESOURCE_ID VARCHAR,
    OLD_VALUE VARIANT,
    NEW_VALUE VARIANT,
    IP_ADDRESS VARCHAR,
    USER_AGENT VARCHAR,
    PAYLOAD VARIANT,
    PRIMARY KEY (AUDIT_EVENT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.AUDIT.SECURITY_EVENT (
    SECURITY_EVENT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    USER_ID NUMBER(38, 0),
    OUTCOME VARCHAR,
    FAILURE_REASON VARCHAR,
    IP_ADDRESS VARCHAR,
    USER_AGENT VARCHAR,
    PAYLOAD VARIANT,
    PRIMARY KEY (SECURITY_EVENT_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.AUDIT.REQUEST_TRACE (
    REQUEST_TRACE_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR,
    OCCURRED_AT TIMESTAMP_TZ,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR,
    CORRELATION_ID VARCHAR NOT NULL,
    REQUEST_ID VARCHAR,
    ENDPOINT VARCHAR NOT NULL,
    METHOD VARCHAR NOT NULL,
    STATUS_CODE NUMBER(10, 0),
    DURATION_MS NUMBER(18, 0),
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    USER_ID NUMBER(38, 0),
    PAYLOAD VARIANT,
    PRIMARY KEY (REQUEST_TRACE_ID)
);
