ALTER TABLE IF EXISTS FERN_REPORTING.AUDIT.AUDIT_EVENT
    ADD COLUMN IF NOT EXISTS MODULE VARCHAR;

ALTER TABLE IF EXISTS FERN_REPORTING.AUDIT.AUDIT_EVENT
    ADD COLUMN IF NOT EXISTS OUTCOME VARCHAR;

ALTER TABLE IF EXISTS FERN_REPORTING.AUDIT.SECURITY_EVENT
    ADD COLUMN IF NOT EXISTS CORRELATION_ID VARCHAR;

ALTER TABLE IF EXISTS FERN_REPORTING.AUDIT.SECURITY_EVENT
    ADD COLUMN IF NOT EXISTS MODULE VARCHAR;

ALTER TABLE IF EXISTS FERN_REPORTING.AUDIT.REQUEST_TRACE
    ADD COLUMN IF NOT EXISTS MODULE VARCHAR;
