CREATE SCHEMA IF NOT EXISTS FERN_REPORTING.FINANCE_PROJECTION;

CREATE TABLE IF NOT EXISTS FERN_REPORTING.FINANCE_PROJECTION.ACCOUNTING_POSTING_PROJECTION (
    POSTING_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    ACCOUNT_CODE VARCHAR NOT NULL,
    DEBIT_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    CREDIT_AMOUNT NUMBER(18, 2) NOT NULL DEFAULT 0,
    CURRENCY_CODE VARCHAR,
    REFERENCE_TYPE VARCHAR,
    REFERENCE_ID VARCHAR,
    PAYLOAD VARIANT,
    PRIMARY KEY (POSTING_ID)
);

CREATE TABLE IF NOT EXISTS FERN_REPORTING.FINANCE_PROJECTION.RECONCILIATION_SNAPSHOT (
    SNAPSHOT_ID NUMBER(38, 0) AUTOINCREMENT,
    SOURCE_EVENT_ID VARCHAR NOT NULL,
    SOURCE_SERVICE VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    OCCURRED_AT TIMESTAMP_TZ NOT NULL,
    INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    IDEMPOTENCY_KEY VARCHAR NOT NULL,
    REGION_ID NUMBER(38, 0),
    OUTLET_ID NUMBER(38, 0),
    BUSINESS_DATE DATE NOT NULL,
    SNAPSHOT_TYPE VARCHAR NOT NULL,
    SNAPSHOT_VALUE NUMBER(18, 2) NOT NULL DEFAULT 0,
    SNAPSHOT_PAYLOAD VARIANT,
    PRIMARY KEY (SNAPSHOT_ID)
);
