export { ExchangeRateManagementPage } from './ExchangeRateManagementPage'
export { RegionsPage } from './RegionsPage'
export { RegionDetailPage } from './RegionDetailPage'
export { OutletsPage } from './OutletsPage'
export { OutletDetailPage } from './OutletDetailPage'
export { OutletCreatePage } from './OutletCreatePage'
